#version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account_statement_backend
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - ./pdf:/app/pdf
      - ./pdf_test:/app/pdf_test
      - ./pdf_output:/app/pdf_output
      - ./scrapper:/app/scrapper
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=mybackend.settings
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: account_statement_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
